import os

def write_file(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Created:", path)

# ============================================================
# 2. utils/unpaired_contrastive.py - CUT-style unpaired contrastive loss
# ============================================================
write_file(r"F:\VQVAE\utils\unpaired_contrastive.py", [
    '"""utils/unpaired_contrastive.py - CUT-style unpaired contrastive loss',
    '',
    'Key insight: translation itself provides supervision.',
    'Take unpaired motion_A, translate to B via shared codebook,',
    'then contrast encoder features at corresponding temporal positions.',
    'This does NOT require paired A-B data.',
    '"""',
    '',
    'import torch',
    'import torch.nn as nn',
    'import torch.nn.functional as F',
    '',
    '',
    'class UnpairedContrastiveLoss(nn.Module):',
    '    """',
    '    CUT-style temporal patch contrastive loss.',
    '    ',
    '    Flow: motion_A -> Enc_A -> VQ -> Dec_B -> motion_B_hat',
    '          Then contrast Enc_A(motion_A)[t] with Enc_B(motion_B_hat)[t]',
    '          Positive: same temporal position t',
    '          Negative: different temporal positions s != t',
    '    """',
    '    def __init__(self, temperature=0.07, num_patches=8):',
    '        super().__init__()',
    '        self.temperature = temperature',
    '        self.num_patches = num_patches',
    '',
    '    def forward(self, feat_A, feat_B_translated):',
    '        """',
    '        feat_A:           Encoder_A output features (B, T, C)',
    '        feat_B_translated: Encoder_B(B_hat) output features (B, T, C)',
    '        ',
    '        Returns: scalar loss',
    '        """',
    '        B, T, C = feat_A.shape',
    '        device = feat_A.device',
    '',
    '        # Randomly sample temporal patches to reduce computation',
    '        if T > self.num_patches:',
    '            idx = torch.randperm(T, device=device)[:self.num_patches]',
    '            idx = idx.sort()[0]  # keep temporal order for consistency',
    '            feat_A = feat_A[:, idx, :]',
    '            feat_B_translated = feat_B_translated[:, idx, :]',
    '',
    '        P = feat_A.shape[1]  # num patches',
    '',
    '        # L2 normalize',
    '        feat_A = F.normalize(feat_A, dim=-1)',
    '        feat_B_translated = F.normalize(feat_B_translated, dim=-1)',
    '',
    '        # Flatten batch and patch dims: (B*P, C)',
    '        q = feat_A.reshape(B * P, C)',
    '        k = feat_B_translated.reshape(B * P, C)',
    '',
    '        # Similarity matrix: (B*P, B*P)',
    '        sim = torch.matmul(q, k.T) / self.temperature',
    '',
    '        # Diagonal = same temporal position = positive pairs',
    '        # Off-diagonal = different positions = negative pairs',
    '        labels = torch.arange(B * P, device=device)',
    '',
    '        # Bidirectional InfoNCE',
    '        loss = (F.cross_entropy(sim, labels) + F.cross_entropy(sim.T, labels)) / 2',
    '',
    '        return loss',
    '',
    '',
    'class UnpairedContrastiveLossSimple(nn.Module):',
    '    """',
    '    Simpler version: contrast global motion embeddings.',
    '    For each sample in batch, treat A->B translation as positive pair.',
    '    """',
    '    def __init__(self, temperature=0.07):',
    '        super().__init__()',
    '        self.temperature = temperature',
    '',
    '    def forward(self, emb_A, emb_B_translated):',
    '        """',
    '        emb_A: (B, C) global embedding of original A motion',
    '        emb_B_translated: (B, C) global embedding of translated B motion',
    '        """',
    '        emb_A = F.normalize(emb_A, dim=-1)',
    '        emb_B_translated = F.normalize(emb_B_translated, dim=-1)',
    '',
    '        sim = torch.matmul(emb_A, emb_B_translated.T) / self.temperature',
    '        labels = torch.arange(emb_A.shape[0], device=emb_A.device)',
    '',
    '        loss = (F.cross_entropy(sim, labels) + F.cross_entropy(sim.T, labels)) / 2',
    '        return loss',
])

# ============================================================
# 3. models/urdf_encoder.py - Embodiment embedding from URDF
# ============================================================
write_file(r"F:\VQVAE\models\urdf_encoder.py", [
    '"""models/urdf_encoder.py - Embodiment embedding for multi-robot support',
    '',
    'Level 1: Simple per-robot learnable embedding (current)',
    'Level 2: URDF graph encoder (future, for diverse robots)',
    '"""',
    '',
    'import torch',
    'import torch.nn as nn',
    '',
    '',
    'class EmbodimentEmbedding(nn.Module):',
    '    """',
    '    Level 1: Simple per-robot learnable embedding.',
    '    Each robot gets a unique ID -> learnable embedding vector.',
    '    ',
    '    Usage:',
    '        emb = EmbodimentEmbedding(num_robots=2, emb_dim=256)',
    '        emb_A = emb(robot_id=0)  # (B,) -> (B, 256)',
    '        emb_B = emb(robot_id=1)',
    '    """',
    '    def __init__(self, num_robots=2, emb_dim=256):',
    '        super().__init__()',
    '        self.embedding = nn.Embedding(num_robots, emb_dim)',
    '        self.emb_dim = emb_dim',
    '',
    '    def forward(self, robot_id):',
    '        """',
    '        robot_id: int or LongTensor of shape (B,)',
    '        Returns: (B, emb_dim)',
    '        """',
    '        if isinstance(robot_id, int):',
    '            device = self.embedding.weight.device',
    '            robot_id = torch.tensor([robot_id], device=device, dtype=torch.long)',
    '        return self.embedding(robot_id)',
    '',
    '',
    'class EmbodimentDecoderWrapper(nn.Module):',
    '    """',
    '    Wraps decoder to accept embodiment embedding as conditioning.',
    '    Concatenates embodiment embedding to decoder input.',
    '    """',
    '    def __init__(self, decoder, emb_dim=256):',
    '        super().__init__()',
    '        self.decoder = decoder',
    '        self.emb_proj = nn.Linear(emb_dim, decoder.output_emb_width if hasattr(decoder, "output_emb_width") else 512)',
    '',
    '    def forward(self, x, emb):',
    '        """',
    '        x: (B, C, T) decoder input features',
    '        emb: (B, emb_dim) embodiment embedding',
    '        Returns: decoder output',
    '        """',
    '        emb_proj = self.emb_proj(emb).unsqueeze(-1)  # (B, C, 1)',
    '        x_cond = x + emb_proj.expand(-1, -1, x.shape[-1])',
    '        return self.decoder(x_cond)',
])

print("=== Phase 2 complete ===")
