import os

def w(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Created:", os.path.basename(path))

# ============================================================
# 9. train_maskgit.py - Train MaskGIT on frozen VQ-VAE tokens
# ============================================================
w(r"F:\VQVAE\train_maskgit.py", [
    '"""',
    'train_maskgit.py - Train MaskGIT discrete diffusion on VQ token space',
    '',
    'Requires: pretrained CrossEmbodimentVQVAE checkpoint',
    'Freezes VQ-VAE, trains MaskGITGenerator on token sequences.',
    'Supports separate generators for robot A and B, or shared generator.',
    '"""',
    '',
    'import os, json, warnings',
    'warnings.filterwarnings("ignore")',
    '',
    'import torch, torch.optim as optim',
    'from torch.utils.tensorboard import SummaryWriter',
    '',
    'import models.vqvae as vqvae',
    'import utils.utils_model as utils_model',
    'import options.option_vq as option_vq',
    'from models.maskgit_generator import MaskGITGenerator',
    '',
    'from dataset.dataset_A import DATALoader as DataLoaderA',
    'from dataset.dataset_B_v4 import DATALoader as DataLoaderB',
    '',
    '',
    'def cycle(iterable):',
    '    while True:',
    '        for x in iterable:',
    '            yield x',
    '',
    '',
    'if __name__ == "__main__":',
    '    # ========== 1. Config ==========',
    '    args = option_vq.get_args_parser()',
    '    torch.manual_seed(args.seed)',
    '    args.out_dir = os.path.join(args.out_dir, args.exp_name + "_maskgit")',
    '    os.makedirs(args.out_dir, exist_ok=True)',
    '',
    '    logger = utils_model.get_logger(args.out_dir)',
    '    writer = SummaryWriter(args.out_dir)',
    '',
    '    import wandb',
    '    wandb.init(project="Crossbody-MaskGIT", name=args.exp_name, config=vars(args))',
    '',
    '    # ========== 2. Load & freeze VQ-VAE ==========',
    '    logger.info("Loading VQ-VAE checkpoint: %s", args.ckpt_path)',
    '    vqvae_model = vqvae.CrossEmbodimentVQVAE(',
    '        input_dim_A=134, input_dim_B=363,',
    '        nb_code=args.nb_code, code_dim=args.code_dim,',
    '        output_emb_width=args.output_emb_width,',
    '        down_t=args.down_t, stride_t=args.stride_t,',
    '        width=args.width, depth=args.depth,',
    '        dilation_growth_rate=args.dilation_growth_rate,',
    '        activation=args.activation, norm=args.norm,',
    '        quantizer_type=args.quantizer_type, mu=args.mu,',
    '    ).cuda()',
    '',
    '    ckpt = torch.load(args.ckpt_path, map_location="cuda", weights_only=False)',
    '    vqvae_model.load_state_dict(ckpt.get("net", ckpt), strict=True)',
    '    vqvae_model.eval()',
    '    for p in vqvae_model.parameters():',
    '        p.requires_grad = False',
    '    logger.info("VQ-VAE frozen.")',
    '',
    '    # ========== 3. Datasets (for token extraction) ==========',
    '    train_txt = os.path.join(args.split_txt_dir, "train.txt")',
    '    train_loader_A = DataLoaderA(args.data_dir_A, train_txt, args.stat_dir_A, args.batch_size, args.window_size)',
    '    train_loader_B = DataLoaderB(args.data_dir_B, train_txt, args.stat_dir_B, args.batch_size, args.window_size)',
    '',
    '    iter_A = cycle(train_loader_A)',
    '    iter_B = cycle(train_loader_B)',
    '',
    '    # ========== 4. MaskGIT generator ==========',
    '    # Shared generator for both robots (trained on mixed tokens)',
    '    generator = MaskGITGenerator(',
    '        vocab_size=args.nb_code, code_dim=args.code_dim, max_len=32,',
    '        cond_dim=256, num_layers=6, num_heads=8, dropout=0.1,',
    '    ).cuda()',
    '',
    '    gen_optimizer = optim.AdamW(generator.parameters(), lr=args.lr, betas=(0.9, 0.99))',
    '    gen_scheduler = optim.lr_scheduler.CosineAnnealingLR(gen_optimizer, T_max=args.total_iter)',
    '',
    '    # ========== 5. Condition embeddings ==========',
    '    cond_A = torch.zeros(args.batch_size, 256, device="cuda")',
    '    cond_B = torch.ones(args.batch_size, 256, device="cuda") * 0.1',
    '',
    '    # ========== 6. Training loop ==========',
    '    logger.info("Training MaskGIT generator...")',
    '    for nb_iter in range(args.total_iter):',
    '        # Alternate between A and B tokens',
    '        if nb_iter % 2 == 0:',
    '            motion, _ = next(iter_A)',
    '            motion = motion.cuda().float()',
    '            cond = cond_A[:motion.shape[0]]',
    '            with torch.no_grad():',
    '                tokens = vqvae_model.encode_A(motion)',
    '        else:',
    '            motion, _ = next(iter_B)',
    '            motion = motion.cuda().float()',
    '            cond = cond_B[:motion.shape[0]]',
    '            with torch.no_grad():',
    '                tokens = vqvae_model.encode_B(motion)',
    '',
    '        loss = generator.compute_loss(tokens, cond, mask_ratio=0.5)',
    '',
    '        gen_optimizer.zero_grad()',
    '        loss.backward()',
    '        torch.nn.utils.clip_grad_norm_(generator.parameters(), max_norm=1.0)',
    '        gen_optimizer.step()',
    '        gen_scheduler.step()',
    '',
    '        if nb_iter % args.print_iter == 0:',
    '            gs = nb_iter',
    '            writer.add_scalar("MaskGIT/loss", loss.item(), gs)',
    '            wandb.log({"MaskGIT/loss": loss.item()}, step=gs)',
    '            logger.info("Iter %6d | Loss=%.4f", nb_iter, loss.item())',
    '',
    '        if nb_iter % args.save_iter == 0:',
    '            ckpt_path = os.path.join(args.out_dir, "maskgit_iter%07d.pth" % nb_iter)',
    '            torch.save(dict(generator=generator.state_dict(), iter=nb_iter), ckpt_path)',
    '            logger.info("MaskGIT checkpoint -> %s", ckpt_path)',
    '',
    '    logger.info("MaskGIT training complete!")',
])

# ============================================================
# 10. eval_cross_embodiment_v3.py - 363-dim evaluation
# ============================================================
w(r"F:\VQVAE\eval_cross_embodiment_v3.py", [
    '"""',
    'eval_cross_embodiment_v3.py - Evaluation for 363-dim cross-embodiment VQ-VAE',
    '',
    'Metrics: Feature MSE, 3D MPJPE (via FK), Foot Skating, Jerk',
    'Supports paired and unpaired evaluation.',
    '"""',
    '',
    'import torch, numpy as np, os, argparse',
    'from os.path import join as pjoin',
    'from tqdm import tqdm',
    '',
    'from models.vqvae import CrossEmbodimentVQVAE',
    'from utils.physics_losses import FKPositionLoss, PhysicsMetrics, G1_363_SLICES, G1_N_JOINTS, G1_CONTACT_JOINTS',
    '',
    '',
    'def load_model(ckpt_path, device):',
    '    model = CrossEmbodimentVQVAE(',
    '        input_dim_A=134, input_dim_B=363,',
    '        nb_code=512, code_dim=512, output_emb_width=512,',
    '        down_t=2, stride_t=2, width=512, depth=3,',
    '        dilation_growth_rate=3,',
    '        activation="relu", norm=None, quantizer_type="ema_reset",',
    '    ).to(device)',
    '    ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)',
    '    model.load_state_dict(ckpt.get("net", ckpt), strict=True)',
    '    model.eval()',
    '    return model',
    '',
    '',
    'def evaluate_paired(model, smpl_dir, g1_dir, g1_mean, g1_std, test_names, device, fk_fn, max_samples=100):',
    '    """A->B translation vs GT B."""',
    '    paired = [n for n in test_names if os.path.exists(pjoin(smpl_dir, n+".npy"))',
    '              and os.path.exists(pjoin(g1_dir, n+".npy"))]',
    '    samples = paired[:max_samples]',
    '',
    '    feat_mses, mpjpes, foot_skatings, jerks = [], [], [], []',
    '    skipped = 0',
    '',
    '    for name in tqdm(samples, desc="Paired eval"):',
    '        fA = np.load(pjoin(smpl_dir, name+".npy"))',
    '        fB_gt = np.load(pjoin(g1_dir, name+".npy"))',
    '',
    '        fA_t = torch.from_numpy(fA).float().unsqueeze(0).to(device)',
    '        fB_gt_t = torch.from_numpy(fB_gt).float().unsqueeze(0).to(device)',
    '',
    '        with torch.no_grad():',
    '            fB_hat, _, _ = model.forward_AB(fA_t)',
    '',
    '        min_len = min(fB_hat.shape[1], fB_gt_t.shape[1])',
    '        if min_len < 10:',
    '            skipped += 1; continue',
    '',
    '        fB_hat_aligned = fB_hat[:, :min_len]',
    '        fB_gt_aligned = fB_gt_t[:, :min_len]',
    '',
    '        # Feature MSE',
    '        feat_mses.append(F.mse_loss(fB_hat_aligned, fB_gt_aligned).item())',
    '',
    '        # 3D MPJPE via FK',
    '        rs, re = G1_363_SLICES["rot_data"]',
    '        pred_rot = fB_hat_aligned[..., rs:re].reshape(1, min_len, G1_N_JOINTS, 6)',
    '        gt_rot = fB_gt_aligned[..., rs:re].reshape(1, min_len, G1_N_JOINTS, 6)',
    '',
    '        fk_pred = fk_fn.fk(pred_rot.reshape(min_len, G1_N_JOINTS, 6)).reshape(1, min_len, G1_N_JOINTS, 3)',
    '        fk_gt = fk_fn.fk(gt_rot.reshape(min_len, G1_N_JOINTS, 6)).reshape(1, min_len, G1_N_JOINTS, 3)',
    '',
    '        mpjpe = (fk_pred - fk_gt).norm(dim=-1).mean().item()',
    '        mpjpes.append(mpjpe)',
    '',
    '        # Physics metrics',
    '        phy = PhysicsMetrics.compute(fB_hat_aligned, fB_gt_aligned)',
    '        foot_skatings.append(phy.get("foot_skating", 0))',
    '        jerks.append(phy.get("jerk", 0))',
    '',
    '    print("  Skipped %d short samples" % skipped)',
    '    print("  Feature MSE:    %.6f" % np.mean(feat_mses))',
    '    print("  3D MPJPE (m):   %.4f" % np.mean(mpjpes))',
    '    print("  Foot Skating:   %.6f" % np.mean(foot_skatings))',
    '    print("  Jerk:           %.6f" % np.mean(jerks))',
    '',
    '    return dict(feat_mse=np.mean(feat_mses), mpjpe=np.mean(mpjpes),',
    '                foot_skating=np.mean(foot_skatings), jerk=np.mean(jerks))',
    '',
    '',
    'def main():',
    '    parser = argparse.ArgumentParser()',
    '    parser.add_argument("--ckpt", type=str, required=True)',
    '    parser.add_argument("--data_dir_A", type=str, required=True)',
    '    parser.add_argument("--data_dir_B", type=str, required=True)',
    '    parser.add_argument("--stat_dir_B", type=str, required=True)',
    '    parser.add_argument("--split_txt", type=str, required=True)',
    '    parser.add_argument("--save_dir", type=str, default="./eval_results_v3")',
    '    parser.add_argument("--max_samples", type=int, default=100)',
    '    parser.add_argument("--device", type=str, default="cuda")',
    '    args_eval = parser.parse_args()',
    '',
    '    device = torch.device(args_eval.device if torch.cuda.is_available() else "cpu")',
    '    print("Device:", device)',
    '',
    '    model = load_model(args_eval.ckpt, device)',
    '    fk_fn = FKPositionLoss().to(device)',
    '',
    '    with open(args_eval.split_txt) as f:',
    '        test_names = [l.strip() for l in f if l.strip()]',
    '',
    '    g1_mean = np.load(pjoin(args_eval.stat_dir_B, "Mean.npy"))',
    '    g1_std = np.load(pjoin(args_eval.stat_dir_B, "Std.npy"))',
    '',
    '    # Paired evaluation',
    '    print("=" * 60)',
    '    print("Paired Evaluation (A->B vs GT B)")',
    '    print("=" * 60)',
    '    results = evaluate_paired(model, args_eval.data_dir_A, args_eval.data_dir_B,',
    '                               g1_mean, g1_std, test_names, device, fk_fn, args_eval.max_samples)',
    '',
    '    # Unpaired generation',
    '    print("\\n" + "=" * 60)',
    '    print("Unpaired Generation (A only -> B)")',
    '    print("=" * 60)',
    '    os.makedirs(args_eval.save_dir, exist_ok=True)',
    '    unpaired = [n for n in test_names',
    '                if os.path.exists(pjoin(args_eval.data_dir_A, n+".npy"))',
    '                and not os.path.exists(pjoin(args_eval.data_dir_B, n+".npy"))]',
    '    saved = 0',
    '    for name in tqdm(unpaired[:50], desc="Generating"):',
    '        fA = np.load(pjoin(args_eval.data_dir_A, name+".npy"))',
    '        fA_t = torch.from_numpy(fA).float().unsqueeze(0).to(device)',
    '        with torch.no_grad():',
    '            fB_hat, _, _ = model.forward_AB(fA_t)',
    '        np.save(pjoin(args_eval.save_dir, "gen_%s.npy" % name), fB_hat.squeeze(0).cpu().numpy())',
    '        saved += 1',
    '    print("Generated %d motions -> %s/" % (saved, args_eval.save_dir))',
    '',
    '',
    'if __name__ == "__main__":',
    '    main()',
])

print("=== All P2 files created ===")
