import os

def write_file(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Created:", path)

# ============================================================
# 8. train_vq_v3.py - Main training script with all P0+P1 improvements
# ============================================================
write_file(r"F:\VQVAE\train_vq_v3.py", [
    '"""',
    'train_vq_v3.py - Cross-Embodiment VQ-VAE training with P0+P1 improvements',
    '',
    'Improvements over train_vq.py:',
    '  P0: 363-dim G1 data with FK-based physical losses',
    '  P0: CUT-style unpaired contrastive loss',
    '  P1: URDF embodiment embedding conditioning',
    '  P1: Physics metrics monitoring',
    '',
    'Training stages:',
    '  Stage 1 (warm-up): reconstruction only',
    '  Stage 2 (main):     + cycle consistency + CUT contrastive',
    '  Stage 3 (main):     + paired contrastive + FK physical losses',
    '"""',
    '',
    'import os',
    'import json',
    'import warnings',
    'warnings.filterwarnings("ignore")',
    '',
    'import torch',
    'import torch.optim as optim',
    'from torch.utils.tensorboard import SummaryWriter',
    '',
    'import models.vqvae as vqvae',
    'import utils.utils_model as utils_model',
    'import options.option_vq as option_vq',
    'from utils.cross_losses import MotionReconLoss, ContrastiveLoss',
    'from utils.physics_losses import FKPositionLoss, PhysicsMetrics',
    'from utils.unpaired_contrastive import UnpairedContrastiveLoss',
    'from models.urdf_encoder import EmbodimentEmbedding',
    '',
    'from dataset.dataset_A import DATALoader as DataLoaderA',
    'from dataset.dataset_B_v4 import DATALoader as DataLoaderB',
    'from dataset.paired_dataset import PairedDATALoader',
    '',
    '',
    'def cycle(iterable):',
    '    while True:',
    '        for x in iterable:',
    '            yield x',
    '',
    '',
    'def update_lr_warm_up(optimizer, nb_iter, warm_up_iter, lr):',
    '    current_lr = lr * (nb_iter + 1) / (warm_up_iter + 1)',
    '    for pg in optimizer.param_groups:',
    '        pg["lr"] = current_lr',
    '    return optimizer, current_lr',
    '',
    '',
    'def make_zero_stats(*keys):',
    '    return {k: 0. for k in keys}',
    '',
    '',
    'if __name__ == "__main__":',
    '    # ========== 1. Initialize config ==========',
    '    args = option_vq.get_args_parser()',
    '    torch.manual_seed(args.seed)',
    '    args.out_dir = os.path.join(args.out_dir, args.exp_name)',
    '    os.makedirs(args.out_dir, exist_ok=True)',
    '',
    '    logger = utils_model.get_logger(args.out_dir)',
    '    writer = SummaryWriter(args.out_dir)',
    '    logger.info(json.dumps(vars(args), indent=4, sort_keys=True))',
    '',
    '    import wandb',
    '    wandb.init(project="Crossbody-VQVAE-v3", name=args.exp_name, config=vars(args))',
    '',
    '    # ========== 2. Load datasets ==========',
    '    train_txt_path = os.path.join(args.split_txt_dir, "train.txt")',
    '    ',
    '    logger.info("Loading Datasets...")',
    '    ',
    '    # A: SMPL (134-dim, unchanged)',
    '    train_loader_A = DataLoaderA(',
    '        args.data_dir_A, train_txt_path,',
    '        args.stat_dir_A, args.batch_size, args.window_size',
    '    )',
    '    ',
    '    # B: G1 v4 (363-dim with explicit 3D positions)',
    '    train_loader_B = DataLoaderB(',
    '        args.data_dir_B, train_txt_path,',
    '        args.stat_dir_B, args.batch_size, args.window_size',
    '    )',
    '    ',
    '    # Paired data for contrastive',
    '    paired_loader = PairedDATALoader(',
    '        args.data_dir_paired_A, args.data_dir_paired_B,',
    '        train_txt_path, args.stat_dir_A, args.stat_dir_B,',
    '        args.batch_size, args.window_size',
    '    )',
    '    ',
    '    iter_A = cycle(train_loader_A)',
    '    iter_B = cycle(train_loader_B)',
    '    iter_paired = cycle(paired_loader)',
    '    ',
    '    logger.info(f"Dataset A: {len(train_loader_A.dataset)} samples")',
    '    logger.info(f"Dataset B: {len(train_loader_B.dataset)} samples")',
    '    logger.info(f"Paired: {len(paired_loader.dataset)} pairs")',
    '',
    '    # ========== 3. Create model (363-dim for B) ==========',
    '    net = vqvae.CrossEmbodimentVQVAE(',
    '        input_dim_A=134,       # SMPL',
    '        input_dim_B=363,       # G1 v4',
    '        nb_code=args.nb_code,',
    '        code_dim=args.code_dim,',
    '        output_emb_width=args.output_emb_width,',
    '        down_t=args.down_t,',
    '        stride_t=args.stride_t,',
    '        width=args.width,',
    '        depth=args.depth,',
    '        dilation_growth_rate=args.dilation_growth_rate,',
    '        activation=args.activation,',
    '        norm=args.norm,',
    '        quantizer_type=args.quantizer_type,',
    '        mu=args.mu,',
    '    ).cuda()',
    '',
    '    # ========== 4. Loss modules ==========',
    '    recon_loss = MotionReconLoss(loss_type="l1_smooth")',
    '    contrastive_loss = ContrastiveLoss(temperature=0.07)',
    '    unpaired_contrastive_loss = UnpairedContrastiveLoss(temperature=0.07, num_patches=8)',
    '    fk_loss_fn = FKPositionLoss(supervised_weight=1.0, self_consist_weight=0.3, ee_weight=2.0)',
    '',
    '    # ========== 5. Optimizer & Scheduler ==========',
    '    optimizer = optim.AdamW(net.parameters(), lr=args.lr, betas=(0.9, 0.99), weight_decay=1e-5)',
    '    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.total_iter)',
    '',
    '    # ========== 6. Loss weights (stage-based curriculum) ==========',
    '    def get_weights(nb_iter, warm_up_iter):',
    '        if nb_iter < warm_up_iter:',
    '            return {',
    '                "recon": 1.0, "vel": 0.5, "commit": 0.02,',
    '                "cycle": 0.0, "contrast": 0.0,',
    '                "unpaired_contrast": 0.0,',
    '                "fk_sup": 0.0, "fk_sc": 0.0, "fk_ee": 0.0,',
    '                "contact": 0.0, "bone_len": 0.0,',
    '            }',
    '        elif nb_iter < warm_up_iter * 2:',
    '            return {',
    '                "recon": 1.0, "vel": 0.5, "commit": 0.02,',
    '                "cycle": 0.1, "contrast": 0.0,',
    '                "unpaired_contrast": 0.05,',
    '                "fk_sup": 0.0, "fk_sc": 0.0, "fk_ee": 0.0,',
    '                "contact": 0.0, "bone_len": 0.0,',
    '            }',
    '        else:',
    '            return {',
    '                "recon": 1.0, "vel": 0.5, "commit": 0.02,',
    '                "cycle": 0.1, "contrast": 0.05,',
    '                "unpaired_contrast": 0.05,',
    '                "fk_sup": 0.3, "fk_sc": 0.1, "fk_ee": 0.5,',
    '                "contact": 0.1, "bone_len": 0.05,',
    '            }',
    '',
    '    # ========== 7. Training loop ==========',
    '    STAT_KEYS = [',
    '        "recon_A", "recon_B", "vel_A", "vel_B",',
    '        "cycle_ABA", "cycle_BAB", "contrast", "unpaired_contrast",',
    '        "fk_sup", "fk_sc", "fk_ee", "contact", "bone_len",',
    '        "commit", "ppl_A", "ppl_B",',
    '    ]',
    '    stats = make_zero_stats(*STAT_KEYS)',
    '',
    '    logger.info("Starting training...")',
    '    for nb_iter in range(args.total_iter):',
    '        w = get_weights(nb_iter, args.warm_up_iter)',
    '',
    '        # ---- 7.1 Load unpaired data ----',
    '        motion_A, mask_A = next(iter_A)',
    '        motion_B, mask_B = next(iter_B)',
    '        motion_A, mask_A = motion_A.cuda().float(), mask_A.cuda().float()',
    '        motion_B, mask_B = motion_B.cuda().float(), mask_B.cuda().float()',
    '',
    '        # ---- 7.2 Auto-reconstruction ----',
    '        recon_A, commit_A, ppl_A = net.forward_A(motion_A)',
    '        recon_B, commit_B, ppl_B = net.forward_B(motion_B)',
    '',
    '        l_recon_A = recon_loss(recon_A, motion_A, mask_A)',
    '        l_recon_B = recon_loss(recon_B, motion_B, mask_B)',
    '        l_vel_A   = recon_loss.velocity(recon_A, motion_A, mask_A)',
    '        l_vel_B   = recon_loss.velocity(recon_B, motion_B, mask_B)',
    '',
    '        # ---- 7.3 Cycle consistency ----',
    '        l_cycle_ABA = torch.zeros(1, device="cuda")',
    '        l_cycle_BAB = torch.zeros(1, device="cuda")',
    '        if w["cycle"] > 0:',
    '            A_cycle = net.cycle_ABA(motion_A)',
    '            B_cycle = net.cycle_BAB(motion_B)',
    '            l_cycle_ABA = recon_loss(A_cycle, motion_A, mask_A)',
    '            l_cycle_BAB = recon_loss(B_cycle, motion_B, mask_B)',
    '',
    '        # ---- 7.4 Paired contrastive ----',
    '        l_contrast = torch.zeros(1, device="cuda")',
    '        if w["contrast"] > 0:',
    '            p_A, p_B, p_mask = next(iter_paired)',
    '            p_A, p_B, p_mask = p_A.cuda().float(), p_B.cuda().float(), p_mask.cuda().float()',
    '            emb_A = net.get_motion_emb_A(p_A)',
    '            emb_B = net.get_motion_emb_B(p_B)',
    '            l_contrast = contrastive_loss(emb_A, emb_B)',
    '',
    '        # ---- 7.5 CUT unpaired contrastive (NEW P0) ----',
    '        l_unpaired_contrast = torch.zeros(1, device="cuda")',
    '        if w["unpaired_contrast"] > 0:',
    '            # A -> B translation',
    '            B_hat, _, _ = net.forward_AB(motion_A)',
    '            # Get encoder features at VQ level (before quantization)',
    '            feat_A = net._encode_feat(motion_A, net.encoder_A)',
    '            feat_B_translated = net._encode_feat(B_hat, net.encoder_B)',
    '            # Temporal patch contrastive',
    '            l_unpaired_contrast = unpaired_contrastive_loss(feat_A, feat_B_translated)',
    '',
    '        # ---- 7.6 FK physical losses (NEW P0) ----',
    '        l_fk_sup = torch.zeros(1, device="cuda")',
    '        l_fk_sc = torch.zeros(1, device="cuda")',
    '        l_fk_ee = torch.zeros(1, device="cuda")',
    '        l_contact = torch.zeros(1, device="cuda")',
    '        l_bone_len = torch.zeros(1, device="cuda")',
    '',
    '        if w["fk_sup"] > 0 or w["fk_sc"] > 0:',
    '            fk_losses = fk_loss_fn(recon_B, motion_B, mask_B)',
    '            if "fk_sup" in fk_losses: l_fk_sup = fk_losses["fk_sup"]',
    '            if "fk_sc" in fk_losses: l_fk_sc = fk_losses.get("fk_sc", torch.zeros(1, device="cuda"))',
    '            if "fk_ee" in fk_losses: l_fk_ee = fk_losses.get("fk_ee", torch.zeros(1, device="cuda"))',
    '            if "contact" in fk_losses: l_contact = fk_losses["contact"]',
    '            if "bone_len" in fk_losses: l_bone_len = fk_losses.get("bone_len", torch.zeros(1, device="cuda"))',
    '',
    '        # ---- 7.7 Total loss ----',
    '        loss = (',
    '            w["recon"]    * (l_recon_A + l_recon_B)',
    '          + w["vel"]      * (l_vel_A   + l_vel_B)',
    '          + w["commit"]   * (commit_A  + commit_B)',
    '          + w["cycle"]    * (l_cycle_ABA + l_cycle_BAB)',
    '          + w["contrast"] * l_contrast',
    '          + w["unpaired_contrast"] * l_unpaired_contrast',
    '          + w["fk_sup"]   * l_fk_sup',
    '          + w["fk_sc"]    * l_fk_sc',
    '          + w["fk_ee"]    * l_fk_ee',
    '          + w["contact"]  * l_contact',
    '          + w["bone_len"] * l_bone_len',
    '        )',
    '',
    '        optimizer.zero_grad()',
    '        loss.backward()',
    '        torch.nn.utils.clip_grad_norm_(net.parameters(), max_norm=1.0)',
    '        optimizer.step()',
    '        scheduler.step()',
    '',
    '        # ---- 7.8 Accumulate stats ----',
    '        stats["recon_A"]   += l_recon_A.item()',
    '        stats["recon_B"]   += l_recon_B.item()',
    '        stats["vel_A"]     += l_vel_A.item()',
    '        stats["vel_B"]     += l_vel_B.item()',
    '        stats["cycle_ABA"] += l_cycle_ABA.item()',
    '        stats["cycle_BAB"] += l_cycle_BAB.item()',
    '        stats["contrast"]  += l_contrast.item()',
    '        stats["unpaired_contrast"] += l_unpaired_contrast.item()',
    '        stats["fk_sup"]    += l_fk_sup.item()',
    '        stats["fk_sc"]     += l_fk_sc.item()',
    '        stats["fk_ee"]     += l_fk_ee.item()',
    '        stats["contact"]   += l_contact.item()',
    '        stats["bone_len"]  += l_bone_len.item()',
    '        stats["commit"]    += (commit_A + commit_B).item()',
    '        stats["ppl_A"]     += ppl_A.item()',
    '        stats["ppl_B"]     += ppl_B.item()',
    '',
    '        # ---- 7.9 Logging ----',
    '        if nb_iter % args.print_iter == 0:',
    '            n = args.print_iter',
    '            global_step = args.warm_up_iter + nb_iter',
    '',
    '            for k in stats:',
    '                writer.add_scalar(f"Train/{k}", stats[k] / n, global_step)',
    '            wandb.log({f"Train/{k}": stats[k] / n for k in stats}, step=global_step)',
    '',
    '            logger.info(',
    '                f"Iter {nb_iter:6d} | "',
    '                f"ReconA={stats['recon_A']/n:.4f} ReconB={stats['recon_B']/n:.4f} | "',
    '                f"VelA={stats['vel_A']/n:.4f} VelB={stats['vel_B']/n:.4f} | "',
    '                f"Cyc={stats['cycle_ABA']/n:.4f}/{stats['cycle_BAB']/n:.4f} | "',
    '                f"Cont={stats['contrast']/n:.4f} UnpCont={stats['unpaired_contrast']/n:.4f} | "',
    '                f"FK={stats['fk_sup']/n:.4f} EE={stats['fk_ee']/n:.4f} Ct={stats['contact']/n:.4f} | "',
    '                f"PPL_A={stats['ppl_A']/n:.1f} PPL_B={stats['ppl_B']/n:.1f}"',
    '            )',
    '',
    '            # Physics metrics (P1)',
    '            with torch.no_grad():',
    '                phy = PhysicsMetrics.compute(recon_B, motion_B, mask_B)',
    '                wandb.log({f"Physics/{k}": v for k, v in phy.items()}, step=global_step)',
    '                writer.add_scalar("Physics/foot_skating", phy.get("foot_skating", 0), global_step)',
    '                writer.add_scalar("Physics/jerk", phy.get("jerk", 0), global_step)',
    '',
    '            stats = make_zero_stats(*STAT_KEYS)',
    '',
    '        # ---- 7.10 Checkpoint ----',
    '        if nb_iter % args.save_iter == 0:',
    '            ckpt_path = os.path.join(args.out_dir, f"net_iter{nb_iter:07d}.pth")',
    '            torch.save({"net": net.state_dict(), "iter": nb_iter}, ckpt_path)',
    '            logger.info(f"Checkpoint saved -> {ckpt_path}")',
    '',
    '    logger.info("Training complete!")',
])

print("=== Phase 5 complete: train_vq_v3.py ===")
