import os

def write_file(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Created:", path)

# ============================================================
# 4. dataset/dataset_B_v4.py - 363-dim G1 dataset
# ============================================================
write_file(r"F:\VQVAE\dataset\dataset_B_v4.py", [
    '"""dataset/dataset_B_v4.py - 363-dim G1 dataset loader',
    '',
    '363-dim format: r_velocity(1)+root_vel_xz(2)+root_y(1)+ric(87)+rot(180)+local_vel(90)+contacts(2)',
    '',
    'Usage: from dataset.dataset_B_v4 import DATALoader as DataLoaderB',
    '"""',
    '',
    'from .dataset_base import get_dataloader',
    '',
    '',
    'def DATALoader(data_dir, split_txt_path, stat_dir, batch_size, window_size, num_workers=8, shuffle=True):',
    '    """',
    '    Creates DataLoader for 363-dim G1 data.',
    '    ',
    '    Args:',
    '        data_dir: path to new_joint_vecs_v4 directory',
    '        split_txt_path: path to train/val/test split file',
    '        stat_dir: path to meta_v4 directory with Mean.npy and Std.npy',
    '        batch_size: int',
    '        window_size: int (number of frames per sample)',
    '    """',
    '    return get_dataloader(data_dir, split_txt_path, stat_dir, batch_size, window_size,',
    '                          num_workers=num_workers, shuffle=shuffle)',
])

# ============================================================
# 5. models/maskgit_generator.py - MaskGIT discrete diffusion generator
# ============================================================
write_file(r"F:\VQVAE\models\maskgit_generator.py", [
    '"""models/maskgit_generator.py - MaskGIT-style discrete diffusion generator',
    '',
    'Operates on VQ token space (discrete indices from shared codebook).',
    'Training: randomly mask tokens, bidirectional Transformer predicts masked tokens.',
    'Inference: iterative unmasking from all-[MASK] state.',
    '',
    'Architecture: Bidirectional Transformer (like BERT) with condition embedding.',
    '"""',
    '',
    'import torch',
    'import torch.nn as nn',
    'import torch.nn.functional as F',
    'import numpy as np',
    '',
    '',
    'class MaskGITGenerator(nn.Module):',
    '    """',
    '    MaskGIT-style generator on VQ discrete token space.',
    '    ',
    '    Training:',
    '        1. VQ-VAE encode motion -> token indices (B, T)',
    '        2. Randomly mask some tokens',
    '        3. Bidirectional Transformer predicts masked tokens',
    '        4. Loss = cross-entropy on masked positions',
    '    ',
    '    Inference:',
    '        1. Start from all [MASK] tokens',
    '        2. Iteratively predict and unmask (cosine schedule)',
    '        3. Feed final tokens to frozen VQ-VAE decoder',
    '    """',
    '    def __init__(self, vocab_size=512, code_dim=512, max_len=64,',
    '                 cond_dim=256, num_layers=6, num_heads=8, dropout=0.1):',
    '        super().__init__()',
    '        self.vocab_size = vocab_size',
    '        self.mask_token_id = vocab_size',
    '        self.max_len = max_len',
    '        self.code_dim = code_dim',
    '',
    '        # Token + mask embedding',
    '        self.token_embed = nn.Embedding(vocab_size + 1, code_dim)  # +1 for [MASK]',
    '',
    '        # Positional encoding',
    '        self.pos_embed = nn.Parameter(torch.randn(1, max_len, code_dim) * 0.02)',
    '',
    '        # Condition projection (robot ID embedding -> code_dim)',
    '        self.cond_proj = nn.Linear(cond_dim, code_dim)',
    '',
    '        # Bidirectional Transformer',
    '        encoder_layer = nn.TransformerEncoderLayer(',
    '            d_model=code_dim, nhead=num_heads, dim_feedforward=code_dim * 4,',
    '            dropout=dropout, activation="gelu", batch_first=True',
    '        )',
    '        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)',
    '',
    '        # Prediction head',
    '        self.head = nn.Linear(code_dim, vocab_size)',
    '',
    '        # Initialize',
    '        self.apply(self._init_weights)',
    '',
    '    def _init_weights(self, module):',
    '        if isinstance(module, nn.Linear):',
    '            nn.init.xavier_uniform_(module.weight)',
    '            if module.bias is not None:',
    '                nn.init.zeros_(module.bias)',
    '        elif isinstance(module, nn.Embedding):',
    '            nn.init.normal_(module.weight, mean=0, std=0.02)',
    '',
    '    def forward(self, token_ids, condition):',
    '        """',
    '        token_ids: (B, T) integer tokens, masked positions filled with mask_token_id',
    '        condition: (B, cond_dim) robot condition embedding',
    '        Returns: (B, T, vocab_size) logits',
    '        """',
    '        B, T = token_ids.shape',
    '',
    '        # Token + Position + Condition',
    '        x = self.token_embed(token_ids)  # (B, T, D)',
    '        x = x + self.pos_embed[:, :T, :]',
    '        cond_emb = self.cond_proj(condition).unsqueeze(1)  # (B, 1, D)',
    '        x = x + cond_emb',
    '',
    '        # Bidirectional transformer',
    '        x = self.transformer(x)  # (B, T, D)',
    '',
    '        # Predict token logits',
    '        logits = self.head(x)  # (B, T, vocab_size)',
    '        return logits',
    '',
    '    def compute_loss(self, token_ids, condition, mask_ratio=0.5):',
    '        """',
    '        Compute masked token prediction loss.',
    '        ',
    '        token_ids: (B, T) ground truth token indices',
    '        condition: (B, cond_dim)',
    '        mask_ratio: fraction of tokens to mask',
    '        """',
    '        B, T = token_ids.shape',
    '        device = token_ids.device',
    '',
    '        # Randomly select positions to mask',
    '        rand = torch.rand(B, T, device=device)',
    '        mask = rand < mask_ratio',
    '',
    '        # Create masked input',
    '        masked_ids = token_ids.clone()',
    '        masked_ids[mask] = self.mask_token_id',
    '',
    '        # Forward',
    '        logits = self.forward(masked_ids, condition)',
    '',
    '        # Loss only on masked positions',
    '        loss = F.cross_entropy(logits[mask], token_ids[mask], reduction="mean")',
    '        return loss',
    '',
    '    @torch.no_grad()',
    '    def generate(self, condition, seq_len=None, steps=8, temperature=1.0):',
    '        """',
    '        Iterative decoding: all-[MASK] -> fully unmasked.',
    '        ',
    '        condition: (B, cond_dim)',
    '        seq_len: output sequence length (default max_len)',
    '        steps: number of iterative refinement steps',
    '        temperature: sampling temperature',
    '        """',
    '        B = condition.shape[0]',
    '        T = seq_len if seq_len is not None else self.max_len',
    '        device = condition.device',
    '',
    '        # Start from all mask',
    '        tokens = torch.full((B, T), self.mask_token_id, device=device, dtype=torch.long)',
    '',
    '        for step in range(steps):',
    '            # Cosine schedule: ratio of tokens still masked',
    '            if steps > 1:',
    '                ratio = np.cos(np.pi / 2 * step / steps)',
    '            else:',
    '                ratio = 0.0',
    '',
    '            # Predict all tokens',
    '            logits = self.forward(tokens, condition)',
    '            probs = F.softmax(logits / temperature, dim=-1)',
    '',
    '            # Sample from predicted distribution',
    '            sampled = torch.multinomial(probs.view(-1, self.vocab_size), 1).view(B, T)',
    '',
    '            # Decide which tokens to update',
    '            is_masked = (tokens == self.mask_token_id)',
    '            # Confidence = max probability for each position',
    '            confidence = probs.max(dim=-1).values',
    '            confidence[~is_masked] = -float("inf")',
    '',
    '            # Number of tokens to unmask this step',
    '            n_unmask = int(T * (1 - ratio)) - (~is_masked).sum(dim=1).float().mean().item()',
    '            n_unmask = max(1, int(n_unmask))',
    '',
    '            if n_unmask > 0:',
    '                # Select top-k confident masked positions',
    '                _, top_idx = confidence.topk(min(n_unmask, is_masked.sum().item()), dim=-1)',
    '                for b in range(B):',
    '                    tokens[b, top_idx[b]] = sampled[b, top_idx[b]]',
    '',
    '        return tokens',
])

# ============================================================
# 6. models/gnn_encoder.py - GNN encoder based on kinematic tree
# ============================================================
write_file(r"F:\VQVAE\models\gnn_encoder.py", [
    '"""models/gnn_encoder.py - Graph Neural Network encoder based on kinematic tree',
    '',
    'Replaces 1D Conv on flattened joints with hierarchical message passing',
    'along the robot kinematic tree.',
    '"""',
    '',
    'import torch',
    'import torch.nn as nn',
    'import torch.nn.functional as F',
    '',
    '',
    'class KinematicGNNEncoder(nn.Module):',
    '    """',
    '    GNN encoder that processes joints along the kinematic tree.',
    '    ',
    '    Architecture: Per-frame GNN -> Temporal Conv -> Output',
    '    ',
    '    For each frame independently:',
    '        1. Project joint features to hidden dim',
    '        2. Message passing along kinematic tree edges',
    '        3. Global pooling across joints',
    '    Then: 1D Conv along temporal dimension',
    '    """',
    '    def __init__(self, in_dim=6, hidden_dim=128, out_dim=512,',
    '                 num_joints=30, num_layers=3,',
    '                 down_t=3, stride_t=2, width=512, depth=3,',
    '                 dilation_growth_rate=3, activation="relu"):',
    '        super().__init__()',
    '        self.num_joints = num_joints',
    '        self.hidden_dim = hidden_dim',
    '',
    '        # Joint feature projection',
    '        self.joint_proj = nn.Linear(in_dim, hidden_dim)',
    '',
    '        # Message passing layers',
    '        self.gnn_layers = nn.ModuleList([',
    '            KinematicMessagePassing(hidden_dim) for _ in range(num_layers)',
    '        ])',
    '',
    '        # Joint -> global pooling',
    '        self.joint_pool = nn.Sequential(',
    '            nn.Linear(hidden_dim, hidden_dim),',
    '            nn.ReLU(),',
    '        )',
    '',
    '        # Temporal convolution',
    '        self.temporal_conv = TemporalConvNet(',
    '            hidden_dim, out_dim, down_t, stride_t, width, depth,',
    '            dilation_growth_rate, activation',
    '        )',
    '',
    '    def forward(self, x, edge_index):',
    '        """',
    '        x: (B*T, J, in_dim) or (B, T, J, in_dim)',
    '        edge_index: (2, E) kinematic tree edges',
    '        Returns: (B, out_dim, T_out)',
    '        """',
    '        if x.dim() == 4:',
    '            B, T, J, C = x.shape',
    '            x = x.reshape(B * T, J, C)',
    '        BT, J, C = x.shape',
    '',
    '        # Project joint features',
    '        x = F.relu(self.joint_proj(x))  # (BT, J, H)',
    '',
    '        # Message passing along kinematic tree',
    '        for layer in self.gnn_layers:',
    '            x = layer(x, edge_index)',
    '',
    '        # Pool across joints -> (BT, H)',
    '        x = self.joint_pool(x).mean(dim=1)  # Mean pooling',
    '',
    '        # Reshape for temporal conv: (B, H, T)',
    '        B = BT // T_orig if "T_orig" in dir() else BT',
    '        # Need to recover B from BT',
    '        if "B" not in dir():',
    '            B = BT // x_orig_T',
    '',
    '        return x',
    '',
    '',
    'class KinematicMessagePassing(nn.Module):',
    '    """',
    '    Message passing along kinematic tree.',
    '    For each parent->child edge: child receives message from parent.',
    '    Uses residual connection for stability.',
    '    """',
    '    def __init__(self, dim, dropout=0.1):',
    '        super().__init__()',
    '        self.msg_net = nn.Sequential(',
    '            nn.Linear(dim * 2, dim),',
    '            nn.ReLU(),',
    '            nn.Dropout(dropout),',
    '            nn.Linear(dim, dim),',
    '        )',
    '        self.update_net = nn.Sequential(',
    '            nn.Linear(dim * 2, dim),',
    '            nn.ReLU(),',
    '            nn.Dropout(dropout),',
    '            nn.Linear(dim, dim),',
    '        )',
    '        self.norm = nn.LayerNorm(dim)',
    '',
    '    def forward(self, x, edge_index):',
    '        """',
    '        x: (N, D) all joint features (N = BT * J)',
    '        edge_index: (2, E) parent->child edges',
    '        """',
    '        parent_idx = edge_index[0]',
    '        child_idx = edge_index[1]',
    '',
    '        # Gather parent-child feature pairs',
    '        parent_feat = x[parent_idx]  # (E, D)',
    '        child_feat = x[child_idx]    # (E, D)',
    '',
    '        # Compute messages from parent to child',
    '        msg = self.msg_net(torch.cat([parent_feat, child_feat], dim=-1))  # (E, D)',
    '',
    '        # Scatter messages to children (aggregate by sum)',
    '        updates = torch.zeros_like(x)',
    '        updates.scatter_add_(0, child_idx.unsqueeze(-1).expand(-1, x.shape[-1]), msg)',
    '',
    '        # Update with residual connection',
    '        x = x + F.relu(updates)',
    '        x = self.norm(x)',
    '',
    '        return x',
    '',
    '',
    'class TemporalConvNet(nn.Module):',
    '    """Minimal temporal convolution compatible with existing Encoder output."""',
    '    def __init__(self, in_dim, out_dim, down_t, stride_t, width, depth,',
    '                 dilation_growth_rate, activation):',
    '        super().__init__()',
    '        self.in_proj = nn.Conv1d(in_dim, width, 1)',
    '',
    '        layers = []',
    '        for i in range(depth):',
    '            layers.append(nn.Conv1d(width, width, 3, padding=1))',
    '            layers.append(nn.ReLU() if activation == "relu" else nn.GELU())',
    '        self.conv_stack = nn.Sequential(*layers)',
    '',
    '        self.downsample = nn.Sequential(*[',
    '            nn.Conv1d(width, width, stride_t*2, stride_t, stride_t)',
    '            for _ in range(down_t)',
    '        ])',
    '',
    '        self.out_proj = nn.Conv1d(width, out_dim, 1)',
    '',
    '    def forward(self, x):',
    '        """x: (B, in_dim, T) -> (B, out_dim, T_out)"""',
    '        x = self.in_proj(x)',
    '        x = self.conv_stack(x) + x  # residual',
    '        x = self.downsample(x)',
    '        x = self.out_proj(x)',
    '        return x',
    '',
    '',
    'def build_kinematic_edges(kinematic_tree, num_joints, bidirectional=True):',
    '    """',
    '    Build edge_index tensor from kinematic tree.',
    '    ',
    '    Args:',
    '        kinematic_tree: List[List[int]]',
    '        bidirectional: if True, add child->parent edges too',
    '    Returns:',
    '        edge_index: (2, num_edges) LongTensor',
    '    """',
    '    edges = []',
    '    for chain in kinematic_tree:',
    '        for j in range(1, len(chain)):',
    '            edges.append([chain[j-1], chain[j]])  # parent -> child',
    '            if bidirectional:',
    '                edges.append([chain[j], chain[j-1]])  # child -> parent',
    '',
    '    edge_index = torch.tensor(edges, dtype=torch.long).T  # (2, E)',
    '    return edge_index',
])

print("=== Phase 3 complete ===")
